### ISSUE TITLE
Feature (FULL): Add socket integration

### ISSUE THREAD

**Issue by vishal2457** [vishal2457/mx#20]
add socket integration with socket io in node server and angular FE

**Comment by Shubham10102000** [comment]
@vishal2457 I think we should store the socket ID along with the user ID in Redis. This way, we can send specialized notifications to specific users. What are your thoughts ?

**Comment by vishal2457** [comment]
@Shubham10102000 yes good idea we will eventually move to storing socket id's in redis.
But it has its complexities like draining socket on server close, removing sockets on disconnect so a basic socket implementation will work as of now.

Also i would suggest to move socket folder into shared folder.
Also see if we could make a common class for socket which could abstract socket methods and share across the app.

**Comment by Shubham10102000** [comment]
@vishal2457 I didn't quite understand your point about making a common class for the socket. We only need to configure the socket once, so why would we need an abstract class for it?
